name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      uses: apt install build-essential pkg-config automake libtool git zlib1g-dev libssl-dev libgeoip-dev libboost-dev libboost-system-dev libboost-chrono-dev libboost-random-dev python3 libtorrent-rasterbar-dev qtbase5-dev qttools5-dev libqt5svg5-dev
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure CXXFLAGS="-std=c++14"
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
