name: GitHub Actions file health check

on:
  push:
    branches: [ '**' ]
  pull_request:
    types: [edited, opened, reopened, synchronize]
    branches: [ '**' ]

jobs:
  check_file_health:
    name: Check file health

    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2.3.3

    - name: install zsh
      run: |
        sudo apt update
        sudo apt install zsh

    - name: run check file health script
      run: |
        ./.github/workflows/file_health.sh
